### PR TITLE
New-ServiceNowChangeRequest.ps1

### PR DESCRIPTION
**Pull request by Dejulia489**
init New-ServiceNowChangeRequest.ps1

### CODE REVIEW

**Comment by Dejulia489** [comment]
@Sam-Martin, Is this still being maintained? If you are no longer maintaining this module I will implement my own internal pipeline and repository. 

Thank you for putting this together by the way!

**Comment by Rick-2CA** [comment]
It's still being maintained, but I've gotten clobbered with other life priorities recently.  I'll try to review your work soon.

**Comment by Dejulia489** [comment]
@Rick-2CA, 

... I know how you feel.

Thank you for the update!

**Comment by Dejulia489** [comment]
@Rick-2CA, 

Following up with respect. 

Thanks, 
Michael

**Comment by Rick-2CA** [comment]
Please look over the revisions below.  I applied the newer parameter formatting (specifically the set names), added a PassThru parameter, added SupportsShouldProcess, and added Try/Catch.  I did a few tweaks in the examples too.  Stuff I need to go through and put into the older functions too.

Please look over the changes and update your commit.  Feel free to call me out if my tweaks don't test well on your end.  Once I can get my hands on a dev instance I'll double check that the parameters hit the out of the box requirements and get the command integrated.

Thank you for taking the time to contribute.

``` PowerShell
function New-ServiceNowChangeRequest {
<#
.SYNOPSIS
    Generates a new ServiceNow change request

.DESCRIPTION
    Generates a new ServiceNow change request using predefined or custom fields by invoking the ServiceNow API

.PARAMETER Caller
    sys_id of the caller of the change request (user Get-ServiceNowUser to retrieve this)

.PARAMETER ShortDescription
    Short description of the change request

.PARAMETER Description
   Long description of the change request

.PARAMETER AssignmentGroup
    sys_id of the assignment group (use Get-ServiceNowUserGroup to retrieve this)

.PARAMETER Comment
    Comment to include in the ticket

.PARAMETER Category
    Category of the change request (e.g. 'Network')

.PARAMETER Subcategory
    Subcategory of the change request (e.g. 'Network')

.PARAMETER ConfigurationItem
    sys_id of the configuration item of the change request

.PARAMETER CustomFields
    Custom fields as hashtable

.PARAMETER ServiceNowCredential
    Credential used to authenticate to ServiceNow

.PARAMETER ServiceNowURL
    The URL for the ServiceNow instance being used (eg: instancename.service-now.com)

.PARAMETER Connection
    Azure Automation Connection object containing username, password, and URL for the ServiceNow instance

.PARAMETER PassThru
    Returns the ticket values after creation

.LINK
    https://github.com/Sam-Martin/servicenow-powershell

.EXAMPLE
    Generate a basic change request attributed to the caller "UserName" with descriptions, categories, assignment groups and CMDB items set.

    New-ServiceNowchange request -Caller UserName -ShortDescription 'New PS change request' -Description 'This change request was created from Powershell' -AssignmentGroup ServiceDesk -Comment 'Inline Comment' -Category Office -Subcategory Outlook -ConfigurationItem UserPC1

.EXAMPLE
    Generate an Change Request by 'splatting' all fields used in the 1st example plus some additional custom ServiceNow fields (These must exist in your ServiceNow instance),  This example uses the caller's sys_id value for identification.

    $newServiceNowChangeRequestSplat = @{
        Caller            = '55ccf91161924edc979d8e7e5627a47d'
        ShortDescription  = 'New PS Change Request'
        Description       = 'This change request was created from Powershell'
        AssignmentGroup   = 'ServiceDesk'
        Comment           = 'Inline Comment'
        Category          = 'Office'
        Subcategory       = 'Outlook'
        ConfigurationItem = 'UserPC1'
        CustomFields      = @{
            u_custom1        = 'Custom Field Entry'
            u_another_custom = 'Related Test'
        }
    }
    New-ServiceNowChangeRequest @newServiceNowChangeRequestSplat
 #>

    [CmdletBinding(DefaultParameterSetName,SupportsShouldProcess)]
    Param(
        [parameter(Mandatory=$true)]
        [string]$Caller,

        [parameter(Mandatory=$true)]
        [string]$ShortDescription,

        [parameter(Mandatory=$false)]
        [string]$Description,

        [parameter(Mandatory=$false)]
        [string]$AssignmentGroup,

        [parameter(Mandatory=$false)]
        [string]$Comment,

        [parameter(Mandatory=$false)]
        [string]$Category,

        [parameter(Mandatory=$false)]
        [string]$Subcategory,

        [parameter(Mandatory=$false)]
        [string]$ConfigurationItem,

        [parameter(Mandatory=$false)]
        [hashtable]$CustomFields,

        [Parameter(ParameterSetName='SpecifyConnectionFields', Mandatory=$True)]
        [ValidateNotNullOrEmpty()]
        [PSCredential]$ServiceNowCredential,

        [Parameter(ParameterSetName='SpecifyConnectionFields', Mandatory=$True)]
        [ValidateNotNullOrEmpty()]
        [string]$ServiceNowURL,

        [Parameter(ParameterSetName='UseConnectionObject', Mandatory=$True)]
        [ValidateNotNullOrEmpty()]
        [Hashtable]$Connection,

        # Switch to allow the results to be passed back
        [Parameter(Mandatory=$false)]
        [switch]$PassThru
    )

    begin {}
    process {
        Try {
            # Create a hash table of any defined parameters (not CustomFields) that have values
            $DefinedChangeRequestParameters = @('AssignmentGroup','Caller','Category','Comment','ConfigurationItem','Description','ShortDescription','Subcategory')
            $TableEntryValues = @{}
            ForEach ($Parameter in $DefinedChangeRequestParameters) {
                If ($null -ne $PSBoundParameters.$Parameter) {
                    # Turn the defined parameter name into the ServiceNow attribute name
                    $KeyToAdd = Switch ($Parameter) {
                        AssignmentGroup     {'assignment_group'}
                        Caller              {'caller_id'}
                        Category            {'category'}
                        Comment             {'comments'}
                        ConfigurationItem   {'cmdb_ci'}
                        Description         {'description'}
                        ShortDescription    {'short_description'}
                        Subcategory         {'subcategory'}
                    }
                    $TableEntryValues.Add($KeyToAdd,$PSBoundParameters.$Parameter)
                }
            }

            # Add CustomFields hash pairs to the Table Entry Values hash table
            If ($null -ne $PSBoundParameters.CustomFields) {
                $DuplicateTableEntryValues = ForEach ($Key in $CustomFields.Keys) {
                    If (($TableEntryValues.ContainsKey($Key) -eq $False)) {
                        # Add the unique entry to the table entry values hash table
                        $TableEntryValues.Add($Key, $CustomFields[$Key])
                    }
                    Else {
                        # Capture the duplicate key name
                        $Key
                    }
                }
            }

            # Throw an error if duplicate fields were provided
            If ($null -ne $DuplicateTableEntryValues) {
                $DuplicateKeyList = $DuplicateTableEntryValues -join ","
                Throw "Ticket fields may only be used once:  $DuplicateKeyList"
            }

            # Table Entry Splat
            $newServiceNowTableEntrySplat = @{
                Table = 'change_request'
                Values = $TableEntryValues
            }

            # Update the splat if the parameters have values
            If ($null -ne $PSBoundParameters.Connection) {
                $newServiceNowTableEntrySplat.Add('Connection', $Connection)
            }
            ElseIf ($null -ne $PSBoundParameters.ServiceNowCredential -and $null -ne $PSBoundParameters.ServiceNowURL) {
                $newServiceNowTableEntrySplat.Add('ServiceNowCredential', $ServiceNowCredential)
                $newServiceNowTableEntrySplat.Add('ServiceNowURL', $ServiceNowURL)
            }

            # Create the table entry
            If ($PSCmdlet.ShouldProcess($Uri,$MyInvocation.MyCommand)) {
                $Result = New-ServiceNowTableEntry @newServiceNowTableEntrySplat

                # Option to return results
                If ($PSBoundParameters.ContainsKey('Passthru')) {
                    $Result
                }
            }
        }
        Catch {
            Write-Error $PSItem
        }
    }
    end {}
}

```

**Comment by Dejulia489** [comment]
@Rick-2CA, 
I implemented the changes you suggested and validated them in my dev instance. This should be ready for your acceptance. 

Thanks again, 
Michael

**Comment by Rick-2CA** [comment]
@Dejulia489 - v1.7.0 has been published.  Thanks, again.

**Comment by Dejulia489** [comment]
@Rick-2CA, 
Thank you!

**Pull request merged**
