### PR TITLE
Adding OAuth support, adding Cattask/variable retrieval

### PR DESCRIPTION
**Pull request by robison-scott**
First time pull request. Apologies if this sucks. 

Edited Set-ServiceNowAuth and Get-ServiceNowTable, created Set-ServiceNowAuthToken. These proposed changes allow OAuth to be used. Token refreshing behavior inconsistent with my account. Access token works fine. Defaults to credentials if token access fails.

Added Get-ServiceNowCatalogTask to pull Cat Tasks from Service-Now. There is an optional -ReturnVariables that uses the last changed file Get-ServiceNowVariables. This one pulls the variables associated with the Cat task down and adds them to the variable field in the $result object.

Final Notes:
- Tokens don't seem to work with the links returned to get the question/answer variables. Thus it uses a web request and the supplied credentials instead. 
- The client ID and client secret are plain text. I'm not fond of that, but anything else seemed hacky.

### CODE REVIEW

**Comment by DexterPOSH** [comment]
@Rick-2CA WHat's the status of this PR?
I see that you are still waiting for @robison-scott to replace Write-Host. Probably that is just a small change and can be done in a separate commit. The PR has some good enhancements that I would like to use.

Let me know if I can help.

**Comment by GilmondRoss** [comment]
@DexterPOSH Anyone could pick this up, to be fair.

**Comment by Rick-2CA** [comment]
@DexterPOSH The delay has strictly been scheduling issues on my side.  I'll see what I can pull off with the time off for this coming holiday.

**Comment by DexterPOSH** [comment]
@Rick-2CA Let me know if you want me to pick this up. I have some time at hand.

**Comment by Rick-2CA** [comment]
@GilmondRoss & @DexterPOSH - I don't have the ability (or perhaps just the know how) to test the OAuth stuff.  Have either of you played with the code to ensure it's functional?

I spent some time with the catalog task and variable functions.  I figured out how to use the API to get the variables.  Get-ServiceNowCatalogTask will get a small change and Get-ServiceNowVariables will be replaced.

**Comment by DexterPOSH** [comment]
@Rick-2CA Let me try this in our test environment and come back. I think it did work last time, but want to re-confirm that.

**Comment by ckite** [comment]
Has anyone gotten OAuth working? I'm starting to dig into this at work and hoping that I won't have to reinvent the wheel. Thanks!

**Comment by Rick-2CA** [comment]
Going to close out this PR.  The changes here were considered and worked further upon by #83.  Interested parties should review where that PR is and provide feedback to the author, please.

**Pull request closed without merging**
