### PR TITLE
Merge the elcooper fork into a dev branch

### PR DESCRIPTION
**Pull request by Rick-2CA**
I tried submitting an update to the elcooper fork and to ask some questions about her approach to the module, but didn't get a reply.  This pull request would pull my edit of that fork into a development branch for a review/consideration.

### CODE REVIEW

**Comment by Sam-Martin** [comment]
Hey @rick-2CA. This looks great, and as I understand it revolves around improving the modules flexibility regarding in automation. Could you add something to the readme explaining this to help people using it and also help me understanding why it's adding please?

**Comment by Sam-Martin** [comment]
Good start! Could you do an example with the `$Connection` object as well please? As that's new too.

**Comment by Rick-2CA** [comment]
ReadMe edit is updated.  I finally figured out the significance of the json file and how it's supposed to work.  The only catch here is I don't have an Azure tenant to test it with.  Seems pretty neat to ditch, but I'd hate to add support for it that I can't confirm too.  Since the parameter expects a hashtable we can still test with a created hash without using Azure, but being as though Azure is the use case...thoughts?

The Get-ConnectionInfo function that was added by another contributor was only integrated into the Remove-ServiceNowTableEntry function.  That work looks incomplete to me, but perhaps I'm missing something.  If you see something I don't (end of PSServiceNow-Tables.psm1) please let me know.

This PR attempt didn't turn out as clean as I'd have liked.  Sorry for my growing pains here.  We can close it out and I'll resubmit after I do better cleanup, we can leave it open and I'll do the cleanup, or accept these changes and I'll do a follow up PR before we consider committing to master.

**Comment by Sam-Martin** [comment]
I'm happy to merge into Dev and cleanup there. Thanks for all the ongoing work!

**Pull request merged**
