### PR TITLE
Testing Merge Behavior for Overhaul

### PR DESCRIPTION
**Pull request by Rick-2CA**

### CODE REVIEW

**Comment by Sam-Martin** [comment]
Hey @Rick-2CA  looks like all the new files have a weird encoding that means they're showing as binary files. If you convert them to UTF-8 we should be able to see the diff :)

**Comment by Rick-2CA** [comment]
Thanks, I hadn't seen that yet.  Was going down the path of what to do about the merge conflicts.  The encoding was corrected.

**Comment by Sam-Martin** [comment]
Don't forget `PSServiceNow-Automation.json` :smile:   
Merge conflicts are tricky, best thing to do is try to merge Master into your overhaul branch locally first, resolve the conflicts, then push your overhaul branch up again which will update the Pull Request and show it as no-conflict.

**Comment by Rick-2CA** [comment]
Seems the json file encoding slipped in when I merged another fork back in March or April.  That's in master.

Thanks for the tips.

**Comment by Rick-2CA** [comment]
Well that was a learning experience.

So it wasn't until this morning I remembered our email about renaming this module to 'ServiceNow'.  Kill this branch, fix the naming, and then merge into dev?

**Comment by Sam-Martin** [comment]
Sounds good to me!

**Pull request closed without merging**
