### PR TITLE
Added Pester test for function 'Update-ServiceNowChangeRequest'.

### PR DESCRIPTION
**Pull request by Turranx**
The Update-ServiceNowChangeRequest test adds a Work Note and a Comment to CHG0000001, which is available in a ServiceNow developer instance.

### CODE REVIEW

**Comment by Rick-2CA** [comment]
@Turranx - Could I get a quick rundown of how the Format function would be utilized?  My ServiceNow dev is gone for a few weeks so I can't pick their brain on what the journal is.  I'd like to be able to put some PowerShell help into the function to explain its use.

**Comment by Turranx** [comment]
I was not expecting you to comment or merge commit 0303eb7.  I was expecting you to review commit 022599d, while I continued to refine and document my next contribution (0303eb7).  Is it possible for you to review and commit just 022599d?  This is my first attempt at contributing to someone else's project, so I'm still trying to find my "sea legs".

**Comment by Rick-2CA** [comment]
Seems like the answer [here](https://stackoverflow.com/questions/36168839/how-to-remove-commits-from-a-pull-request) should get you where you want to be.

**Comment by Rick-2CA** [comment]
This PR had more than intended and wasn't corrected.  The goal of adding a test for Update-ServiceNowChangeRequest was met by other means.  I appreciate the PR and hope we'll see another one day.

**Pull request closed without merging**
